spring:
  profiles:
    active: default
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: greatstartmail@gmail.com
    password: metaPassword
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
    test-connection: true
  messages:
    basename: MessagesBundle
support:
  email: greatstartmail@gmail.com

---
spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        default_schema: startup_platform
    hibernate:
      ddl-auto: update
security:
  basic:
    enabled: false
server:
  port: 8080
---
spring:
  profiles: default
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: startup_platform
security:
  enable-csrf: false
server:
  port: 9001


